POST http://localhost:3000/sign-up
Content-Type: application/json

{
    "firstname":"aa",
    "lastname":"abdulskakour",
    "username":"aa",
    "password":"1",
    "email":"e"
}

###

GET http://localhost:3000/users
Content-Type: application/json

{
    
}

###

POST http://localhost:3000/sign-in
Content-Type: application/json

{
    "firstname":"aa",
    "lastname":"abdulskakour",
    "username":"aa",
    "password":"1",
    "email":"e"
}

###

GET http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjdXN0b21lcl9pZCI6MiwiZmlyc3RfbmFtZSI6ImFhIiwibGFzdF9uYW1lIjoiYWJkdWxza2Frb3VyIiwidXNlcm5hbWUiOiJhYSIsInBhc3N3b3JkIjoiJDJiJDEwJGZkSUxxeVdqcGtNWmtWc243VmtQd3VCU3ROT3ZLRFZJWjUzbTBLMWt5VWhXaEh4NHpKR0FXIiwiZW1haWwiOiJlIiwiaWF0IjoxNjg3ODExMjU4fQ.At7u3I8LrmwFyyPpE12IDSmDgVDcDWV2fZ4w7VUYvCw

###